[package]
name = "a_star_cli"
version = "0.1.0"
authors = ["Peter Eliah Kodl <peter.e.kodl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustbox = "0.11.0"
rayon = "1.5.1"
rand = "0.8.4"
